### ISSUE TITLE
Bot picks itself as a challangee

### ISSUE THREAD

**Issue by GustavPersson** [PaulAsjes/kartbot#3]
Easy to reproduce if it's just you and the bot in a channel.

```
gustav [11:46 AM] 
!fifa

fifabotBOT [11:46 AM] 
Fifa time! Gustav has challenged Fifabot to a game of Fifa!  Room for 2 more!
```

**Comment by PaulAsjes-zz** [comment]
Fixed, kart/fifabot will politely decline a game in a PM and will no longer pick itself in an almost empty channel.
